# Generated by Django 5.2 on 2025-05-05 07:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='기수 번호 (예: 10, 11)', unique=True)),
                ('start_date', models.DateField(help_text='기수 시작일')),
                ('end_date', models.DateField(help_text='기수 종료일')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='학생 이름', max_length=100)),
                ('leadership', models.IntegerField(default=5, help_text='리더십 점수 (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('personality', models.IntegerField(choices=[(1, '매우 내향적'), (2, '내향적'), (3, '중간'), (4, '외향적'), (5, '매우 외향적')], default=3, help_text='사회성/성격 점수 (1: 매우 내향적 ~ 5: 매우 외향적)')),
                ('motivation', models.IntegerField(default=5, help_text='학업 의지 점수 (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('achievement', models.IntegerField(default=5, help_text='성취도 평가 점수 (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('instructor_rating', models.IntegerField(default=5, help_text='강사 평가 점수 (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('peer_rating', models.IntegerField(default=5, help_text='수강생들간 협업 선호도 (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.cohort')),
            ],
            options={
                'ordering': ['cohort', 'name'],
                'unique_together': {('cohort', 'name')},
            },
        ),
    ]
