# Generated by Django 5.2 on 2025-05-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='first_counseling',
            field=models.TextField(blank=True, help_text='1차 상담 내용', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='second_counseling',
            field=models.TextField(blank=True, help_text='2차 상담 내용', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='special_note',
            field=models.TextField(blank=True, help_text='특이사항', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='third_counseling',
            field=models.TextField(blank=True, help_text='3차 상담 내용', null=True),
        ),
    ]
