# Generated by Django 5.2 on 2025-05-05 08:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_first_counseling_student_second_counseling_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=20, help_text='나이', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='student',
            name='is_major',
            field=models.BooleanField(default=False, help_text='전공 여부'),
        ),
    ]
