# Generated by Django 5.2 on 2025-05-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_age_student_is_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', '남자'), ('F', '여자')], default='M', help_text='성별', max_length=1),
        ),
    ]
